PrintComment: ThisGoesHere cleans spawner configs to use LeifHeim ones
DeleteFolder:
- plugins/FixItFelix-ConfigurePlants # removed until updated
- plugins/FixItFelix-Krumpac_Reforge_Reconfigure_Plants # removed until updated
- plugins/FixItFelix-Krumpac_Reforge_Respawned # removed until updated
- plugins/FixItFelix-RegenerativeNature # removed until updated
- plugins/aedenthorn_mods-InstantMonsterLootDrop # removed, since not working, console commands will fail with this one
- plugins/thedefside-BetterUI_Reforged # removed, since not working anymore, no updates
- plugins/hyleanlegend-Rune_Magic # removed, since broken reference to http lib
