PrintComment: ThisGoesHere cleans spawner configs to use LeifHeim ones
DeleteFolder:
- plugins/LVH-IT-UseEquipmentInWater # removal
- plugins/FixItFelix-Diving_reposted # replacement
- plugins/Smoothbrain-Resurrection # removal

