PrintComment: ThisGoesHere cleans up the Krumpac configs to let them be regenerated
DeleteFile:
- config/Datys.Datys_Professions.cfg
- config/Krumpac_Praying_System.cfg
- config/Krumpac.Krumpac_Armors.cfg
- config/Krumpac.Krumpac_Building_Pieces.cfg
- config/Krumpac.Krumpac_Dungeon_Meadows.cfg
#- config/Krumpac.Krumpac_Reforge_Core.cfg
- config/Krumpac.Krumpac_Sacrificing_Altars.cfg
- config/Krumpac.Krumpac_Tribe_Ornaments.cfg
- config/Krumpac.Krumpac_Weapon_Arsenal.cfg

PrintComment: ThisGoesHere overwrites configs with changes
CopyFile:
- src: config/overrides/Krumpac.Krumpac_Reforge_Core.cfg
  dest: config/Krumpac.Krumpac_Reforge_Core.cfg
